# Generated by Django 5.2.8 on 2025-12-20 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_job_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='cover_letter',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='email',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='status',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='stage',
            field=models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('rejected', 'Rejected')], default='applied', max_length=30),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
