# Generated by Django 5.2.8 on 2025-12-21 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_jobapplication_cover_letter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_email', models.EmailField(max_length=254)),
                ('business_email_verified', models.BooleanField(default=False)),
                ('commercial_register_number', models.CharField(max_length=100)),
                ('tax_id', models.CharField(max_length=100)),
                ('verification_document', models.FileField(blank=True, null=True, upload_to='companies/verification_docs/')),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='core.companyprofile')),
            ],
        ),
    ]
