# Generated by Django 5.2.8 on 2025-12-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_job_application_deadline_job_expires_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='expires_at',
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='tax_document',
            field=models.FileField(blank=True, null=True, upload_to='companies/tax_documents/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='application_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
