# Generated by Django 5.2.8 on 2025-12-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_job_expires_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='is_active',
            new_name='is_open',
        ),
        migrations.RemoveField(
            model_name='job',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='status',
        ),
        migrations.RemoveField(
            model_name='job',
            name='vacancies',
        ),
        migrations.AddField(
            model_name='job',
            name='is_promoted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='benefits',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
