# Generated by Django 5.2.8 on 2025-12-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_is_active_job_is_open_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applications_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of applications allowed', null=True),
        ),
    ]
