# Generated by Django 5.2.8 on 2026-01-06 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_emailverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
