# Generated by Django 5.2.8 on 2026-01-06 22:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_useremailverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyEmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification', to='core.companyprofile')),
            ],
        ),
    ]
