# Generated by Django 5.2.8 on 2026-01-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_cvprofile_cvpdf'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cvpdf',
            name='core_cvpdf_user_id_928292_idx',
        ),
        migrations.AddField(
            model_name='cvpdf',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='cvpdf',
            index=models.Index(fields=['user', 'kind'], name='core_cvpdf_user_id_22f72b_idx'),
        ),
        migrations.AddConstraint(
            model_name='cvpdf',
            constraint=models.UniqueConstraint(fields=('user', 'kind'), name='uniq_cvpdf_user_kind'),
        ),
    ]
