# Generated by Django 5.2.8 on 2026-01-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_cvpdf_core_cvpdf_user_id_928292_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cvpdf',
            name='uniq_cvpdf_user_kind',
        ),
        migrations.AddIndex(
            model_name='cvpdf',
            index=models.Index(fields=['user', 'kind', 'is_latest'], name='core_cvpdf_user_id_928292_idx'),
        ),
        migrations.AddConstraint(
            model_name='cvpdf',
            constraint=models.UniqueConstraint(fields=('user', 'kind', 'version'), name='uniq_cvpdf_user_kind_version'),
        ),
    ]
